server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms_consent?useSSL=false&allowPublicKeyRetrieval=true
    username: svc_consent
    password: pw_consent
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    dev.starryeye: DEBUG
