### web browser 에서 수행.. 커스텀 로그인 화면(user / 1111) -> 커스텀 동의 화면 -> redirect uri 로 code 전달
### 일부 scope 만 동의한 뒤 아래 요청을 반복해보면.. 기승인 scope 는 "이미 동의한 권한" 으로, 나머지만 체크박스로 나온다.
GET http://localhost:8091/oauth2/authorize?response_type=code&client_id=my-spring-client&scope=openid profile custom-scope&redirect_uri=http://127.0.0.1:8080/login/oauth2/code/my-spring-client
