### web browser 에서 수행 (user / 1111).. {client id} 는 api.http 로 등록한 CONFIDENTIAL client 의 clientId 로 교체
### 커스텀 로그인 -> 커스텀 동의 -> redirect uri 로 code 전달.. 전 과정이 LB(9000) 를 거치며 매 요청 다른 인스턴스가 처리한다
GET http://localhost:9000/oauth2/authorize?response_type=code&client_id={client id}&scope=openid profile custom-scope&redirect_uri=http://127.0.0.1:8080/login/oauth2/code/my-spring-client
