### OAuth2AuthorizationService 를 이용하여 OAuth2Authorization 을 조회해본다..
GET http://localhost:8091/oauth2-authorization?token=eyJraWQiOiJmYWYzZjQ0My05NmZkLTQyZWEtOWUwZC02NTI4YTg4NDYwOGYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiYXVkIjoibXktc3ByaW5nLWNsaWVudCIsIm5iZiI6MTc0Njk5ODY3NCwic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSIsImN1c3RvbS1zY29wZSJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwOTEiLCJleHAiOjE3NDY5OTg5NzQsImlhdCI6MTc0Njk5ODY3NCwianRpIjoiMGM1NTQzNTUtNzlmNS00YWFlLTg4OTQtYmU2Njk1ZGUwNzEwIn0.B12zvGAyuCdzm0PZl3fGwVxJ4d9LA23D13Kr4gTjOt4LUUU4CFrq5pVv1HvKjnTY8ZX-ivziJWp9MHCn5dPRvuB6mBTLfjnWaCMbNpdAFRKxCEJuSMkKdPBmoqhBkILoM8taRuBjKut4lM9YnyaLLxFMjzHrCCce6wYNPqAjTOnRcSzbtYVSwA0c-9EYbBn53UoWcIJLWNFjniEtJ2h0XtTFGWREGbgZTWNjz5FyZ9NLg2wbediZ60IBljCGnDvORk5xTNa4ozzE-ymy8IOdvXcziXdiBmvLJNKVLB3vixwF6HsZwfCVPb4GfvF9O36_4w2E2h9ZmuCBQ_k-GqSAJQ