server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/custom_oauth2_authorization_consent_service
    username: root
    password: 1111
  jpa:
    hibernate:
      # 서버를 재기동해도 동의 기록(OAuth2AuthorizationConsent)이 유지되는 것을 확인하기 위해 update 로 설정
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    org.springframework.security: DEBUG
