### .well-known, OAuth 2.0
GET http://localhost:8091/.well-known/oauth-authorization-server

### .well-known, OAuth 2.0 + OpenID Connect
GET http://localhost:8091/.well-known/openid-configuration

### userinfo
GET http://localhost:8091/userinfo
Authorization: Bearer eyJraWQiOiIyZTdjZGE0MC0xODU2LTQ4NzQtOGU3Zi1mNjhhNTQ3YWVkYjkiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiYXVkIjoibXktc3ByaW5nLWNsaWVudCIsIm5iZiI6MTc0Njc5NTg1MSwic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSIsImN1c3RvbS1zY29wZSJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwOTEiLCJleHAiOjE3NDY3OTYxNTEsImlhdCI6MTc0Njc5NTg1MSwianRpIjoiYzM5YjgxZGMtZTEyNy00YWJlLThiY2YtZmI4Zjg0NzMyOGFlIn0.G8W-tLxbaRiUeJR3SwWWnqJ8ByROuW6bebkuHIn4roYV25BXf_HcvsMIC-hO6joGPDFLAfJ2iA0xTutRayMgERvnpn2ZCYm7L06mXofxtEioyWpigEXumgr6YLZMjNLxjT8quRNqPkZu680sF761sy-wb-ypltlKAv9x6abrCVmmWHqkmsKgqlA1euFPUcb_uap1uIv76djXOTdkyYWBHaFU7KMCklEJKL_ij4iIOns8V8FvLdqmzsw8SWdhgvKP6M6yn_NJHEDcPKp7yJw4sZyKE7Aw39N0wt85hU-AR2c9U9QOEj3kr6O498OoVSvFqbiZ4ycaPa2qJmPMnXKcFw