### GET 메서드는 CSRF 보안에 포함되지 않아서 응답이 정상적으로 리턴된다.
GET http://localhost:8080/api/articles

### POST 메서드는 CSRF 보안 대상이므로 막힘, 응답 데이터에 "_csrf" 토큰을 준다. 해당 토큰을 포함시키면 성공됨
POST http://localhost:8080/api/articles/new
Content-Type: application/json

{
  "title": "good article"
}

### csrf 토큰을 포함시키면 통과됨
POST http://localhost:8080/api/articles/new?_csrf=WMrYVWj41ljzmTF5v5PwDjTIPWNZfvvhFq9kB5df0LqNwOHobazoZwya4mneqldNjb7EbQT-EFtoHMjMd8xWNPY9sY_p9YeN
Content-Type: application/json

{
  "title": "good article"
}

### csrf 토큰을 포함시키면 통과됨 2
POST http://localhost:8080/api/articles/new
Content-Type: application/json
X-Csrf-Token: WMrYVWj41ljzmTF5v5PwDjTIPWNZfvvhFq9kB5df0LqNwOHobazoZwya4mneqldNjb7EbQT-EFtoHMjMd8xWNPY9sY_p9YeN

{
  "title": "good article"
}