### GET 메서드는 CSRF 보안에 포함되지 않아서 응답이 정상적으로 리턴된다.
GET http://localhost:8080/api/articles

### POST 메서드는 CSRF 보안 대상이므로 막힘, 응답 데이터에 "_csrf" 토큰을 준다. 해당 토큰을 포함시키면 성공됨
POST http://localhost:8080/api/articles/new
Content-Type: application/json

{
  "title": "good article"
}

### csrf 토큰을 포함시키면 통과됨
POST http://localhost:8080/api/articles/new?_csrf=ma6V5Uf2czZzd_x7X2ZwHmMOSsdrBKRMnQI2SsBEWvUgX-Z5r8ig3XfPRQJeFc5DZ0tEK1M_Z_5ZM5Rh_DBScqN0a5MZZ4IY
Content-Type: application/json

{
  "title": "good article"
}

### csrf 토큰을 포함시키면 통과됨 2
POST http://localhost:8080/api/articles/new
Content-Type: application/json
X-Csrf-Token: ma6V5Uf2czZzd_x7X2ZwHmMOSsdrBKRMnQI2SsBEWvUgX-Z5r8ig3XfPRQJeFc5DZ0tEK1M_Z_5ZM5Rh_DBScqN0a5MZZ4IY

{
  "title": "good article"
}


### 현재 csrf 토큰 조회
GET http://localhost:8080/csrf