### api key success
GET http://localhost:8080/admin
X-API-KEY: keyofadmin

### api key fail
GET http://localhost:8080/admin
X-API-KEY: wrongkey


### jwt token, success
### Precondition : WebBrowser 로 접근하여 login 필요함
GET http://localhost:8080/api
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NDQ3MzMyMTYsInN1YiI6InVzZXIiLCJpYXQiOjE3NDQ3Mjk2MTZ9.9wjUpG0XC2mXi_QcQoAg9EgvBYPvA__tPk0MwbX7Kec

### parent AuthenticationManager 인 DaoAuthenticationManager 가 작동 되는지 확인
GET