apiVersion: v1
kind: ServiceAccount
metadata:
  name: signing
  namespace: microservice-as
---
apiVersion: v1
kind: Service
metadata:
  name: signing
  namespace: microservice-as
spec:
  selector:
    app: signing
  ports:
    - name: http
      port: 8083
      targetPort: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: signing
  namespace: microservice-as
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signing
  template:
    metadata:
      labels:
        app: signing
    spec:
      serviceAccountName: signing
      containers:
        - name: signing
          image: signing:local
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8083
