server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver: # OAuth2ResourceServerProperties
        jwt:
          jwk-set-uri: http://localhost:8091/oauth2/jwks

logging:
  level:
    org.springframework.security: DEBUG
