server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms_client_registry?useSSL=false&allowPublicKeyRetrieval=true
    username: svc_client_registry
    password: pw_client_registry
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    dev.starryeye: DEBUG
