### confidential client
### confidential client 가 authorization server 로 직접 introspect 하는 경우..
### body 의 token_type_hint 는 Optional 이라 생략함.
### 자세한 설명은 pkce 디렉토리 go
POST http://localhost:8091/oauth2/introspect
Content-Type: application/x-www-form-urlencoded
Authorization: Basic bXktc3ByaW5nLWNsaWVudDpzZWNyZXQ=

token=eyJraWQiOiJiMzYzZDY5MC02ZGM0LTRkZDMtOTAzMi02M2IzM2QyMjE5MWUiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiYXVkIjoibXktc3ByaW5nLWNsaWVudCIsIm5iZiI6MTc0ODAwNDAzOCwic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSIsImN1c3RvbS1zY29wZSJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwOTEiLCJleHAiOjE3NDgwMDQzMzgsImlhdCI6MTc0ODAwNDAzOCwianRpIjoiYTZhYWQzMzgtYmVlYy00M2QxLWIxODItNGI1MDlmYzlkOGIyIn0.SBcU8gJfAMj9HN_f2P4RBiSO6_nVMOP7rMeWxNzMA2p5SV29Gee98zmccUXtg-uL6KLn3FfBYOq2JaqkoBYFo4aBTsiF-tx--H5v9Xg_D6ICFrnq6Y3VoZ27bJkN6seC_izdRhB1hh-DBLQN0YmN1hjRF8Jv39x0Z2F5ID06rUtUpasNbx7uJC_T0xpjh9YkHbTK2BcxogMZWfsW_S21t_exlt8vAGdwWsaAOyxzqWB6uiQh0HgvkdywJrde3K22HTC6RSelMRjvVQdW72VzgZUHqvNZB4x8GEFAOMK2ge9S9VkhN2xC5xr8rvuan6Vky0v2C9JudHzGDuUCh1qPww
