### generate JWT by MAC
POST http://localhost:8080/token
Content-Type: application/json

{
  "username": "user",
  "password": "1111"
}

### verify JWT, success
GET http://localhost:8080
Authorization: Bearer eyJraWQiOiJyc2FLZXkiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJzdWIiOiJ1c2VyIiwiZXhwIjoxNzQ1MjUxNTcxLCJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwidXNlcm5hbWUiOiJ1c2VyIn0.guIPoyBpn4NN8H4Z5-ARGs-F9Pll6N7aT1wHeI0tWvdLD5xJLdjKZkwde4FrOVwmmvkXQsHrSkq2T41sw4nmKCTGsBIdVeghBzJUdP3-B3CW6jVnqQJX0Y8GkZuXyo0H0FhyryrC5uzHyzYO7An1puvCtcsM9xe_uhqpV7-Fvkt88OM-qMhfAm4IGwpAUdwkciLtsBr7-7mB5qmI0TwKxoZWbddltYcNN1rGs-4XiMhcwgVT07wSQ_NWlg-N1UGIVJ6ygBtbAINz-mq9_mhdvqlS3QD2P9XvfLWVWAPH3-k-4rEUAoL7dSRqCz6hcnD6BHadY7J9PC_7CMRM4p402w


### verify JWT, fail 1
GET http://localhost:8080
Authorization: aaaa

### verify JWT, fail 1
GET http://localhost:8080
Authorization: Bearer aaaa

### 토큰없이 요청
GET http://localhost:8080