server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver: # OAuth2ResourceServerProperties
        jwt:
          jwk-set-uri: http://localhost:8090/realms/custom-realm/protocol/openid-connect/certs
#          issuer-uri: http://localhost:8090/realms/custom-realm
#          public-key-location: classpath:certs/publicKey.txt
#          audiences: http://localhost:8080
#          jws-algorithms: RS256