server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:

          my-keycloak:
#            authorization-grant-type: authorization_code
#            client-authentication-method: client_secret_basic
            client-id: custom-client-app
            client-secret: kAjcXgrLnfPZNRcqjdynH5uO0ACiqK6y
            client-name: My keycloak
            scope: openid,email,profile
            redirect-uri: http://localhost:8080/login/oauth2/code/my-keycloak
            provider: my-keycloak

          # https://console.cloud.google.com/auth
          my-google:
#            authorization-grant-type: authorization_code
#            client-authentication-method: client_secret_basic
            client-id:
            client-secret:
#            client-name: My Google
#            scope: openid,email,profile
#            redirect-uri: http://localhost:8080/login/oauth2/code/my-google
            provider: google # CommonOAuth2Provider

          # https://developers.naver.com/apps
          my-naver:
            authorization-grant-type: authorization_code
#            client-authentication-method: client_secret_basic
            client-id:
            client-secret:
            client-name: My Naver
            scope: email,profile # non-openid
            redirect-uri: http://localhost:8080/login/oauth2/code/my-naver
            provider: my-naver

          # https://developers.kakao.com/
          my-kakao:
#            authorization-grant-type: authorization_code
#            client-authentication-method: client_secret_basic
            client-id:
            client-secret:
            client-name: My Kakao
            scope: openid,profile_nickname,profile_image,account_email
            redirect-uri: http://localhost:8080/login/oauth2/code/my-kakao
            provider: my-kakao

        provider:
          my-keycloak: # http://localhost:8090/realms/custom-realm/.well-known/openid-configuration
            issuer-uri: http://localhost:8090/realms/custom-realm
#            authorization-uri: http://localhost:8090/realms/custom-realm/protocol/openid-connect/auth
#            jwk-set-uri: http://localhost:8090/realms/custom-realm/protocol/openid-connect/certs
#            token-uri: http://localhost:8090/realms/custom-realm/protocol/openid-connect/token
#            user-info-uri: http://localhost:8090/realms/custom-realm/protocol/openid-connect/userinfo
            user-name-attribute: sub
          my-naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # todo
          my-kakao: # https://kauth.kakao.com/.well-known/openid-configuration
            issuer-uri: https://kauth.kakao.com
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v1/oidc/userinfo
            user-name-attribute: sub


