### OpenID Connect RP-Initiated Logout endpoint
### parameter
###     id_token_hint (M) id token 값
###     client_id (O)
###     post_logout_redirect_uri (O) RegisteredClient 에 설정하고 사용하면 logout 작업이 끝나면 해당 uri 로 redirect 시켜준다.
###     state (O) CSRF
### authorize 를 수행한 web browser 에서 수행해서 해당 세션을 폐기 시킨다.
GET http://localhost:8091/connect/logout?id_token_hint=eyJraWQiOiIwMTI4ZDc4Ni02Zjk3LTQzMzItOGY2NS04NTBiYjE4NWRjZGYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiYXVkIjoibXktc3ByaW5nLWNsaWVudCIsImF6cCI6Im15LXNwcmluZy1jbGllbnQiLCJhdXRoX3RpbWUiOjE3NDg1MTk2NzUsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA5MSIsImV4cCI6MTc0ODUyMTU1MCwiaWF0IjoxNzQ4NTE5NzUwLCJqdGkiOiJmYWFlOWNjZi0wZjAyLTQxYzItYTllYS05ZWQ0NmFkNzc4OGQiLCJzaWQiOiJTQlAtSXplLXZoS3FUbmZJZXV0d0Z6eHVuSks4SVBXZzhpNHY2Z0JRNndJIn0.MkSfKIvFeFlEYb4WA9VV_8pdEmzfRq5kgMGZ0tY4l0hiZwCQ4LHybFYbm1dkr_Uut1B0P1CV1VUI0M6k1-em-TrsQ44293Z0SRx8YS1vewg9N2CvLRfIplVvtlzBz8o9je3ZYLuVuWnBwGZOQ7obe3u2Ha2E77P8bfpRzp2BQUB_CnMQVlHDEzVJTI4SnFjQQwtW0P9Z4zstHaRMIFsyi1xBGfco3Y6EHstGyIJFKoF3jHGz47iCHm0bDSW1oS87JitTB427pgG2i59grI2ZJzBGK3MECyfTlrpCB0xei74gzUedGqnEHeVCaBxe7TbObUDeH9bT9Q96yWI57iOcMA

### OpenID Connect RP-Initiated Logout endpoint
### 주의사항.
### authorize 를 web browser 통해서 진행했다면.. 여기서 POST 요청을 보내면.. 이 요청에 대한 세션은 OP 입장에서 없기 때문에 세션 종료가 이루어지지 않음
POST http://localhost:8091/connect/logout
Content-Type: application/x-www-form-urlencoded

id_token_hint=eyJraWQiOiIwMTI4ZDc4Ni02Zjk3LTQzMzItOGY2NS04NTBiYjE4NWRjZGYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiYXVkIjoibXktc3ByaW5nLWNsaWVudCIsImF6cCI6Im15LXNwcmluZy1jbGllbnQiLCJhdXRoX3RpbWUiOjE3NDg1MTk2NzUsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA5MSIsImV4cCI6MTc0ODUyMTQ5MCwiaWF0IjoxNzQ4NTE5NjkwLCJqdGkiOiJjMmU0MWJkNC1iNjFlLTQyYzktOTNjOS1hNjQwYWRlNDIyYmUiLCJzaWQiOiJTQlAtSXplLXZoS3FUbmZJZXV0d0Z6eHVuSks4SVBXZzhpNHY2Z0JRNndJIn0.g4tkrJPkkpaNOWVCqrpk8QVfb716hV2GWR0h4N7mHPWra4JyHw9yyHZa5z3DkR00Atsgu-MAtd1d3xyqJDsLt7UpFhrB1FSfL85Za2chM6lsPOlhaWztUBpxSHgY2IbIpMNgXNDoesoVLYJftYxQfxwNi54OsWj9J5Dwa-SQ1pioiAg4ZRxg6tQ45BU7Ius_iYw1ZO-gxIzkft5PXVO5X4pQumaZU5djlLFyfRnaQgzjSRJWvxPirlEzJ1I7KtTiaeaSVlE8C1bynx7W148rhkFVCSoF-o5W5aluHT4mUzCdd6siaYwLSdVarX2CXvHAvaoFvplK4N07jRPtw7p7jA

