### userinfo endpoint
GET http://localhost:8091/userinfo
Authorization: Bearer eyJraWQiOiI1ZTZkYjM4OS1lNmY1LTQ2NzctYWQyNi0yMGIzYTc3MTNlMmEiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiYXVkIjoibXktc3ByaW5nLWNsaWVudCIsIm5iZiI6MTc0ODUyNTI1Niwic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSIsImN1c3RvbS1zY29wZSJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwOTEiLCJleHAiOjE3NDg1MjU1NTYsImlhdCI6MTc0ODUyNTI1NiwianRpIjoiOGQzYWI4NGMtZDg1NS00N2RhLTkwODQtOGRkZDhiNmNkMzIyIn0.KcXFWa6kn0Vrcvt8XI1b_MmY6Chq3_taZ2XqdKdIC_uaGGzOAw7TqoRjDOHeblZOYUHUbpdJpLXyVKN0rDW4iSj72cE1L3thQlTifex_fT0SUmB3rr95N9IFKkHoSUHpTNxc8I2k5vJcy212PnHgqxi8OgOcUpVrOJT2DzFH3zcxhVdCtYYa2heyGRTQv6UC28oLHNtvzN6j7W7J35_jfJWggFQ0xCNfWxTAjqR0pGcPTovsdSnrskz45YZQE7kxpRIsYbA37T6170px3V1AtxAf8n18uCWh5RHh8f-g68tQxxBCmZQno8EbfZC1dc-fW3GL3QfQIly_Luzzz1UlPg