### userinfo endpoint
GET http://localhost:8091/userinfo
Authorization: Bearer eyJraWQiOiJiNmI0Y2IyMS1hMzY4LTRmNWEtYmM4MS02YWUzOWVhNTExOTUiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiYXVkIjoibXktc3ByaW5nLWNsaWVudCIsIm5iZiI6MTc0ODUyMjM0Mywic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSIsImN1c3RvbS1zY29wZSJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwOTEiLCJleHAiOjE3NDg1MjI2NDMsImlhdCI6MTc0ODUyMjM0MywianRpIjoiMTE3YzM1MzMtYTk0NC00MjdiLWJmYzctYmUwMjZjZDY4MWIyIn0.oMEcYGmRlHww4YHSRhv4lVfb96yg1YFi8OD8UwKFJTdN9-cut7G8gDwJF35v6nmLj8utHhTI2lhj6YHwQzBoWnimsYKptaUszd9uP6RdPOvBGwJFYTV9ygzDG0HTqVjI-5n8fVfoFLrB6XuaUE2wOgDjj34w0akecG7Pzp2l1tBhGnV7fjiov6c4Q4b_iJlgglOH8xDtgHgRAZkcQr1fLy2TkUMOv4rt42FYXyj5Nw5Ma5sYh8FeAgBKK4zN1PeLn9LaRv4XNnz7O_NhDYvVwaLHzRZVYW7Jb9Qon0MSJQCTQR58ops9aS1EClxPLY1gwlo3SF6pOJ9tf2r_wRECKw