server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          my-keycloak:
            client-id: custom-client-credential-app
            client-secret: Yi1wfgNNWDUcpoOPyoQACI6wWc5rOhQb
            authorization-grant-type: client_credentials
            scope: openid,email,profile
        provider:
          my-keycloak:
            issuer-uri: http://localhost:8090/realms/custom-realm
            user-name-attribute: preferred_username
