server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          my-keycloak:
            client-id: custom-client-app-authentication-client
            client-secret: aZponBmHnOggBf8dKNneDO8oMpNZzQgW
            scope: openid,email,profile
            redirect-uri: http://localhost:8080/hello
        provider:
          my-keycloak:
            issuer-uri: http://localhost:8090/realms/custom-realm
            user-name-attribute: preferred_username
