### "/oauth2/token" 요청, SERVICE client (client_credentials 전용)
### client_id, client_secret 은 등록 API(http/api.http) 응답 값으로 교체할 것
POST http://localhost:8091/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&
client_id={client id}&
client_secret={client secret}&
scope=custom-scope
