### login
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "user",
  "password": "1111"
}

### home, 인텔리제이 http 클라이언트에서 cookie 를 자동으로 설정해주지 않는 것같다.. 아래와 같이 직접 설정해주자.
GET http://localhost:8080
Cookie: JSESSIONID=6749779583BC22882AFE5B149DFE24ED;
