server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: custom-client-app
            client-secret: kAjcXgrLnfPZNRcqjdynH5uO0ACiqK6y
#            client-name: custom-client-app
#            authorization-grant-type: authorization_code
#            client-authentication-method: client_secret_basic
            scope: openid,email,profile
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
          google:
            client-id: random
            client-secret: random
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/realms/custom-realm
#            authorization-uri: http://localhost:8090/realms/custom-realm/protocol/openid-connect/auth
#            jwk-set-uri: http://localhost:8090/realms/custom-realm/protocol/openid-connect/certs
#            token-uri: http://localhost:8090/realms/custom-realm/protocol/openid-connect/token
#            user-info-uri: http://localhost:8090/realms/custom-realm/protocol/openid-connect/userinfo
#            user-name-attribute: preferred_username