### web browser 에서 수행, For confidential client
### "/oauth2/authorize", authorization code 발급 요청
GET http://localhost:8091/oauth2/authorize?response_type=code&client_id=my-spring-client&scope=openid profile custom-scope&redirect_uri=http://127.0.0.1:8080/login/oauth2/code/my-spring-client&code_challenge=t8x3Ro9DrxCsLoiHZ-Myd0oIYQPir0z889kONTcviGU&code_challenge_method=S256

### web browser 에서 수행, For public client
### "/oauth2/authorize", authorization code 발급 요청
GET http://localhost:8091/oauth2/authorize?response_type=code&client_id=my-public-client&scope=openid profile custom-scope&redirect_uri=http://127.0.0.1:8080/login/oauth2/code/my-public-client&code_challenge=t8x3Ro9DrxCsLoiHZ-Myd0oIYQPir0z889kONTcviGU&code_challenge_method=S256