spring:
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8091
        client:
          my-client:
            registration:
              client-id: my-client
              client-secret: "{noop}secret"
              client-authentication-methods: [client_secret_basic]
              authorization-grant-types: [authorization_code, refresh_token]
              redirect-uris: [http://localhost:8080/login/oauth2/code/my-client]
              scopes: [openid, profile]
