server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          my-keycloak:
#            authorization-grant-type: authorization_code
#            client-authentication-method: client_secret_basic
            client-id: custom-client-app
            client-secret: kAjcXgrLnfPZNRcqjdynH5uO0ACiqK6y
            client-name: My keycloak
            scope: openid,email,profile
            redirect-uri: http://localhost:8080/login/oauth2/code/my-keycloak
            provider: my-keycloak
          my-google:
#            authorization-grant-type: authorization_code
#            client-authentication-method: client_secret_basic
            client-id:
            client-secret:
#            client-name: My Google
#            scope: openid,email,profile
#            redirect-uri: http://localhost:8080/login/oauth2/code/my-google
            provider: google # CommonOAuth2Provider
          my-naver:
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            client-id:
            client-secret:
            client-name: My Naver
            scope: email,profile # non-openid
            redirect-uri: http://localhost:8080/login/oauth2/code/my-naver
            provider: my-naver
        provider:
          my-keycloak:
            issuer-uri: http://localhost:8090/realms/custom-realm
#            authorization-uri: http://localhost:8090/realms/custom-realm/protocol/openid-connect/auth
#            jwk-set-uri: http://localhost:8090/realms/custom-realm/protocol/openid-connect/certs
#            token-uri: http://localhost:8090/realms/custom-realm/protocol/openid-connect/token
#            user-info-uri: http://localhost:8090/realms/custom-realm/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
          my-naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


