### web browser 에서 프록시 주소(9000)로 수행 (user / 1111 로그인 -> consent 동의 -> redirect uri 로 code 전달됨)
### 로그인/consent 로의 redirect 가 전부 프록시 주소(9000) 기준으로 유지되는 것을 확인해볼 것
GET http://localhost:9000/oauth2/authorize?response_type=code&client_id=my-spring-client&scope=openid profile custom-scope&redirect_uri=http://127.0.0.1:8080/login/oauth2/code/my-spring-client
