### web browser 에서 수행 (user / 1111 로그인 -> consent 동의 -> redirect uri 로 code 전달됨)
### "/oauth2/authorize", authorization code 발급 요청
### client_id 는 등록 API(http/api.http) 응답 값으로 교체할 것
### 이 요청을 처리하는 과정에서 RegisteredClientRepository::findByClientId 가 호출된다. (서버 콘솔의 select 쿼리 확인)
GET http://localhost:8091/oauth2/authorize?response_type=code&client_id={client id}&scope=openid profile custom-scope&redirect_uri=http://127.0.0.1:8080/login/oauth2/code/my-spring-client
