### authorization code 발급, web browser 에서 할 것.
### response_type, client_id, scope, redirect_uri 필요
GET http://localhost:8091/oauth2/authorize?response_type=code&client_id=my-spring-client&scope=openid profile custom-scope&redirect_uri=http://127.0.0.1:8080/login/oauth2/code/my-spring-client