### authorization code grant 방식 1단계 : authorize
###     client 가 resource server 에서 resource owner(사용자)의 자원에 접근하기 위해 authorization server 에 접근 권한을 받는 요청의 1단계이다.
###         2단계에서 access token 을 받기 위해 authorization code 를 발급 받는 요청이다.
###     1. client 는 authorization server 에게 해당 요청(auth)을 보낸다.
###     2. authorization server 는 resource owner 의 승인이 있어야 하므로 로그인 창을 응답한다.
###     3. 로그인 창을 응답 받은 client 는 resource owner 에게 패싱한다.
###     4. resource owner 는 authorization server 로그인을 한다.
###     5. 로그인에 성공하면, authorization server 는 client 가 지정해 놓은 scope (접근 범위) 를 보여주고 동의를 받는다. 동의를 하면..
###     6. authorization server 는 resource owner 에게 redirect 응답을 준다.
###     7. redirect 응답은 authorization server 와 client 가 미리 약속해둔 Authorized rediret URIs (client) 로 요청 보내게 되는 것이다.
###     8. redirect 를 통해 authorization server 는 resource owner 를 거쳐 client 에게 Authorization code 를 발급한다.(url 에 포함)
### response_type : code, Standard flow (Authorization code 를 발급 받는다.)
### client_id : client id
### scope : client 가 resource server 에 접근하여 사용할 정보의 범위
### redirect_url : authorization server 가 발급한 authorized code 를 client 에게 넘겨주기 위한 콜백 주소 (Authorized redirect URIs)
### 참고
###     웹 브라우저에서 수행
###     응답받은 authorization code 는 1회용이다. 한번 사용되면 폐기됨
GET http://localhost:8090/realms/custom-realm/protocol/openid-connect/auth?response_type=code&client_id=custom-client-app&scope=profile email openid&redirect_uri=http://localhost:8080
