### web browser 에서 수행 (user / 1111)
### 비밀번호를 일부러 틀리게 입력해보면 [인증 실패] BadCredentials 감사 로그를, 성공하면 [인증 성공] 로그를 볼 수 있다.
GET http://localhost:8091/oauth2/authorize?response_type=code&client_id=my-spring-client&scope=openid profile custom-scope&redirect_uri=http://127.0.0.1:8080/login/oauth2/code/my-spring-client
